<a href="https://colab.research.google.com/github/toluwatobi/rgu_thesis/blob/main/Thesis_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## Uploading the simulated file

from google.colab import files

uploaded = files.upload()

Saving Report.xlsx to Report.xlsx

In [18]:
## Visaulizing the data

import pandas as pd
report = pd.read_excel(r'Report.xlsx')
report.head()

,sample,H%,N%,Ldis,Ldia,status,Min (kg/s),Mout (kg/s),m H,m CH4,...,Hmf,H1,H2,H3,H4,H5,H6,H7,H8,Hout
0,S1a,0.0,100.0,0.0,0.0,done,0.002486,-0.001639,0.0000,1.0000,...,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,b,20.0,80.0,0.0,0.0,done,0.002049,-0.002581,0.0305,0.9695,...,0.0305,0.029166,0.027751,0.026316,0.025062,0.023888,0.022797,0.021771,0.020819,0.019932
2,c,25.0,75.0,0.0,0.0,done,0.001940,-0.002493,0.0402,0.9598,...,0.0402,0.038352,0.036387,0.034421,0.032706,0.031107,0.029626,0.028242,0.026960,0.025770
3,d,30.0,70.0,0.0,0.0,done,0.001832,-0.002403,0.0511,0.9489,...,0.0511,0.048624,0.045986,0.043383,0.041117,0.039016,0.037078,0.035275,0.033611,0.032072
4,S2a,0.0,100.0,50.0,0.2,done,0.001666,-0.000302,0.0000,1.0000,...,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [19]:
## Selecting the features needed for the modeling

y = report.pop('Ldis')
X = report.copy()
X.drop(['sample', 'Ldia', 'status'], axis = 1, inplace = True)

,H%,N%,Min (kg/s),Mout (kg/s),m H,m CH4,Pin,P1,P2,P3,...,Hmf,H1,H2,H3,H4,H5,H6,H7,H8,Hout
0,0.0,100.0,0.002486,-0.001639,0.0000,1.0000,192.924438,166.997620,147.364777,127.098236,...,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,20.0,80.0,0.002049,-0.002581,0.0305,0.9695,176.535400,153.384933,135.630463,117.134003,...,0.0305,0.029166,0.027751,0.026316,0.025062,0.023888,0.022797,0.021771,0.020819,0.019932
2,25.0,75.0,0.001940,-0.002493,0.0402,0.9598,171.889862,149.475739,132.216812,114.198601,...,0.0402,0.038352,0.036387,0.034421,0.032706,0.031107,0.029626,0.028242,0.026960,0.025770
3,30.0,70.0,0.001832,-0.002403,0.0511,0.9489,167.475815,145.833939,129.144073,111.676979,...,0.0511,0.048624,0.045986,0.043383,0.041117,0.039016,0.037078,0.035275,0.033611,0.032072
4,0.0,100.0,0.001666,-0.000302,0.0000,1.0000,259.274384,226.233368,199.660599,171.931458,...,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [23]:
y.shape

(166,)